baseURL = 'https://shimadotdev.github.io/'
languageCode = 'en-us'
title = 'Shima Dot Dev Blog'
theme = 'hugo-paper'
[params]
  rss = true
  github = 'shimadotdev'
  color = 'linen'
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
